server:
  port: 1113

  cloud:
    config:
      ####读取后缀
      profile: pro
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true


feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 500
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info
  endpoint:
    health:
      show-details: always

